---
triple:          'arm64-apple-darwin'
binary-path:     '/Users/abhijithks/tmpZsh/C-data-structure-codes/src/stack'
relocations:
  - { offsetInCU: 0x26, offset: 0x26, size: 0x8, addend: 0x0, symName: _f_string, symObjAddr: 0x0, symBinAddr: 0x100003BFC, symSize: 0x54 }
  - { offsetInCU: 0x3F, offset: 0x3F, size: 0x8, addend: 0x0, symName: _Scan, symObjAddr: 0x348, symBinAddr: 0x100008000, symSize: 0x0 }
  - { offsetInCU: 0xC6, offset: 0xC6, size: 0x8, addend: 0x0, symName: _Stack, symObjAddr: 0x360, symBinAddr: 0x100008018, symSize: 0x0 }
  - { offsetInCU: 0x1BF, offset: 0x1BF, size: 0x8, addend: 0x0, symName: _f_string, symObjAddr: 0x0, symBinAddr: 0x100003BFC, symSize: 0x54 }
  - { offsetInCU: 0x204, offset: 0x204, size: 0x8, addend: 0x0, symName: _test, symObjAddr: 0x54, symBinAddr: 0x100003C50, symSize: 0x1C }
  - { offsetInCU: 0x219, offset: 0x219, size: 0x8, addend: 0x0, symName: _integer, symObjAddr: 0x70, symBinAddr: 0x100003C6C, symSize: 0xB8 }
  - { offsetInCU: 0x25D, offset: 0x25D, size: 0x8, addend: 0x0, symName: _stack_new, symObjAddr: 0x128, symBinAddr: 0x100003D24, symSize: 0x24 }
  - { offsetInCU: 0x285, offset: 0x285, size: 0x8, addend: 0x0, symName: _main, symObjAddr: 0x14C, symBinAddr: 0x100003D48, symSize: 0x64 }
  - { offsetInCU: 0x2AD, offset: 0x2AD, size: 0x8, addend: 0x0, symName: _pop, symObjAddr: 0x1B0, symBinAddr: 0x100003DAC, symSize: 0x8C }
  - { offsetInCU: 0x2E3, offset: 0x2E3, size: 0x8, addend: 0x0, symName: _push, symObjAddr: 0x23C, symBinAddr: 0x100003E38, symSize: 0xC8 }
  - { offsetInCU: 0x327, offset: 0x327, size: 0x8, addend: 0x0, symName: _node_new, symObjAddr: 0x304, symBinAddr: 0x100003F00, symSize: 0x40 }
...
